services:
  vpn_bot:
    build: .
    container_name: vpn_bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./vpn_bot.db:/app/vpn_bot.db
      - ./photo:/app/photo
      - ./templates:/app/templates